databases:
  - name: servidorElizabeth
    plan: free
    databaseName: dbcine #no mayusculas
    user: elizabeth

services:
  - type: web
    plan: free
    name: cineUTC
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn cineUTC.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: servidorDeya
          property: externalConnectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: cineutc-mb47.onrender.com


# set DATABASE_URL=postgresql://elizabeth:GTqhifHUAXPQx6i0UZbXlbPpTDqXzUKo@dpg-cqlpkig8fa8c73bgsijg-a.oregon-postgres.render.com/dbcine_l5qn